---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-telcoadmin
  annotations:
    argocd.argoproj.io/sync-options: Prune=false   
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: -admiclustern
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: telcoadmin