---
# To manually create this file from pull-secret.json
# oc create secret generic assisted-deployment-pull-secret -n assisted-installer --from-file=.dockerconfigjson=pull-secret.json --type=kubernetes.io/dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.pull_secret_name }}
  namespace: {{ $.Values.gitops.namespace }}
data:
  .dockerconfigjson: >-
    {{ $.Values.global.pull_secret | b64enc }}
type: kubernetes.io/dockerconfigjson
