---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.global.name }}-wait-argocd-job
  namespace: {{ $.Values.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:v1.3.1
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.global.name }}-wait-argocd-job
          env:
            - name: SLEEP
              value: "15"
          command:
            - /bin/bash
            - -c
            - |
              echo "Cluster Pre Install Hook"
              URL_READY="Pausing $SLEEP seconds..."
              echo "Waiting for ArgoCD to install"
              CSV_NAME=$(oc get csv -n openshift-operators  | egrep openshift-gitops-operator | awk '{print $1}')
              CSV_STATUS="Pausing $SLEEP seconds..."
              while [ "$CSV_STATUS" != "Succeeded" ]; do
                echo "Waiting for the GitOps Operator to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                CSV_STATUS=$( oc get csv -n openshift-operators $CSV_NAME -o jsonpath={..status.phase} )
              done
              echo "All done! Hooray!"


