---
kind: Secret
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
data:
  external_cluster_details: >-
    W3tuYW1lOiByb29rLWNlcGgtbW9uLWVuZHBvaW50cywga2luZDogQ29uZmlnTWFwLCBkYXRhOiB7ZGF0YTogaHlwZXJ2aXNvcjEubGFiLmRpa3Rpby5uZXQ9MTkyLjE5LjEzMC4xMTo2Nzg5LCBtYXhNb25JZDogMCwgbWFwcGluZzoge319fSwge25hbWU6IHJvb2stY2VwaC1tb24sIGtpbmQ6IFNlY3JldCwgZGF0YToge2FkbWluLXNlY3JldDogYWRtaW4tc2VjcmV0LCBmc2lkOiBjMmViZDAzNi0zN2FjLTExZWMtOGIzYy03MDhiY2Q0ZTlmNjEsIG1vbi1zZWNyZXQ6IG1vbi1zZWNyZXR9fSwge25hbWU6IHJvb2stY2VwaC1vcGVyYXRvci1jcmVkcywga2luZDogU2VjcmV0LCBkYXRhOiB7dXNlcklEOiBjbGllbnQuaGVhbHRoY2hlY2tlciwgdXNlcktleTogQVFBSS9aSmhtYnkyREJBQU4vVkRQb0F1c01RdjVhd0JHdUpGMVE9PX19LCB7bmFtZTogcm9vay1jc2ktcmJkLW5vZGUsIGtpbmQ6IFNlY3JldCwgZGF0YToge3VzZXJJRDogY3NpLXJiZC1ub2RlLCB1c2VyS2V5OiBBUUFJL1pKaHZZaDREUkFBY0lYbDNIVnFlbzF4YzVUM0YwMVZodz09fX0sIHtuYW1lOiBjZXBoLXJiZCwga2luZDogU3RvcmFnZUNsYXNzLCBkYXRhOiB7cG9vbDogb2NwLWNlcGgtcmJkfX0sIHtuYW1lOiBtb25pdG9yaW5nLWVuZHBvaW50LCBraW5kOiBDZXBoQ2x1c3RlciwgZGF0YToge01vbml0b3JpbmdFbmRwb2ludDogMTkyLjE5LjEzMC4xMiwgTW9uaXRvcmluZ1BvcnQ6IDkyODN9fSwge25hbWU6IHJvb2stY3NpLXJiZC1wcm92aXNpb25lciwga2luZDogU2VjcmV0LCBkYXRhOiB7dXNlcklEOiBjc2ktcmJkLXByb3Zpc2lvbmVyLCB1c2VyS2V5OiBBUUFJL1pKaFc3NC9EaEFBdnVOM3M4WmxYMXlsNks0cGRzekc0UT09fX0sIHtuYW1lOiBjZXBoLXJndywga2luZDogU3RvcmFnZUNsYXNzLCBkYXRhOiB7ZW5kcG9pbnQ6IDE5Mi4xOS4xMzAuMTA6OTQ0MywgcG9vbFByZWZpeDogZGVmYXVsdH19LCB7bmFtZTogcmd3LWFkbWluLW9wcy11c2VyLCBraW5kOiBTZWNyZXQsIGRhdGE6IHthY2Nlc3NLZXk6IEhUTDZNWkhKNzRMSjhXOUVXT0tULCBzZWNyZXRLZXk6IHpScFBjckVoZVZiVlQxM21LalBWMFdhRlhhd0JkWUJMaVVXeHBycWF9fV0K
type: Opaque
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage:
    enable: true
  labelSelector: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  version: 4.8.0
