---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  #annotations:
  #  cluster.ocs.openshift.io/local-devices: 'true'
  #  uninstall.ocs.openshift.io/cleanup-policy: delete
  #  uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
  #uid: de53d9e1-5125-4a61-a050-9287aa95fc97  
  #finalizers:
  #  - storagecluster.ocs.openshift.io
spec:
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - config: {}
      count: 1
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: ocs-local-volume-set
          volumeMode: Block
        status: {}
      name: ocs-deviceset-ocs-local-volume-set
      placement: {}
      preparePlacement: {}
      replica: 3
      resources: {}
