---
# WARNING: ONLY USE THIS FOR MANAGING CLUSTERS NOT FOR REGULAR USERS
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.gitops.namespace }}-cluster-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.gitops.namespace }}-argocd-application-controller
    namespace: {{ $.Values.gitops.namespace }}
  # NOTE: THIS INSTANCE IT IS ONLY FOR CLUSTER ADMINS
  - kind: ServiceAccount
    name: {{ $.Values.gitops.namespace }}-argocd-server
    namespace: {{ $.Values.gitops.namespace }}